### ISSUE TITLE
issue with "Save changes" - LTI Plugin "Options"

### ISSUE THREAD

**Issue by pacesetter-cm** [OSCELOT/wordpress-lti#2]
Hi, 

I was able to get this plugin installed (using your instructions for Composer, on a shared host at Siteground), and I am able to create new platforms using the plugin. 

I am trying to remove the plugin so I can reinstall it on another site that doesn't have other plugins interfering with the login process; however, _**when I try to manage the settings to "Delete all data" etc., I am unable to "Save Options".**_  

![lti-options](https://user-images.githubusercontent.com/96441643/146815698-1459f1af-5bc8-4bba-b1e5-2c3ddb484f80.png)

When attempting to save options, it goes to an "insecure page warning" before submitting. When I choose to "submit anyway", it gives the error that I don't have sufficient permission. This is a superadmin user, who should have the required permissions (like "manage_network_options"). 

Is there a way I can fix this error to be able to remove anything that was put in the database when the plugin is uninstalled?

![permission-error](https://user-images.githubusercontent.com/96441643/146815790-82f3d7df-4a71-42cd-aa05-f6f039499a0c.png)

Should the plugin still work with the current version of Wordpress? I am not very familiar with LTI and still have to learn how to use it; I am hoping this can be used for connecting Wordpress Multisite with any LTI-enabled virtual learning environment? 

Thank You!

**Comment by spvickers** [comment]
Issues with this plugin are best reported in the source code repository at https://github.com/celtic-project/wordpress-lti/ as I believe you have already done (see https://github.com/celtic-project/wordpress-lti/issues/12).  So I shall close this issue here.
